# Generated by Django 4.2.4 on 2024-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage_Contactdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactdetail1_title', models.CharField(max_length=200, null=True)),
                ('contactdetail2_subtitle', models.CharField(max_length=200)),
                ('contactdetail3_phone', models.CharField(max_length=200)),
                ('contactdetail4_email', models.CharField(max_length=200)),
                ('contactdetail5_address', models.CharField(max_length=200)),
                ('contactdetail6_weblink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Advertise_card1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise_card_image', models.ImageField(upload_to='home_Advertise_card1')),
                ('advertise_card_catchline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Advertise_card2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise_card_image', models.ImageField(upload_to='home_Advertise_card2')),
                ('advertise_card_catchline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Car_Booking_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(upload_to='home_Car_Booking_Offer')),
                ('car_rating', models.CharField(max_length=500)),
                ('car_model_name', models.CharField(max_length=200)),
                ('car_rent_location', models.CharField(max_length=200)),
                ('car_odometer_reading', models.CharField(max_length=500)),
                ('car_model_type', models.CharField(max_length=500)),
                ('car_fuel_type', models.CharField(max_length=500)),
                ('car_seat_count', models.CharField(max_length=500)),
                ('car_booking_price', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Flight_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_travel_type', models.CharField(max_length=500)),
                ('flight_image', models.ImageField(upload_to='home_Flight_Offer')),
                ('catchline', models.TextField()),
                ('offered_dealprice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Hotel_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_location', models.CharField(max_length=200)),
                ('hotel_rating', models.CharField(max_length=500)),
                ('hotel_price', models.CharField(max_length=200)),
                ('hotel_image', models.ImageField(upload_to='home_Hotel_Offer')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story1_image', models.ImageField(upload_to='home_Stories')),
                ('story1_name', models.CharField(max_length=200)),
                ('story2_image', models.ImageField(upload_to='home_Stories')),
                ('story2_name', models.CharField(max_length=200)),
                ('story3_image', models.ImageField(upload_to='home_Stories')),
                ('story3_name', models.CharField(max_length=200)),
                ('story4_image', models.ImageField(upload_to='home_Stories')),
                ('story4_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Top_Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_Top_Destination')),
                ('Destination_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Travel_By_Activity_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_card_image', models.ImageField(upload_to='home_Travel_By_Activity_Card')),
                ('activity_card_tour_count', models.CharField(max_length=200)),
                ('activity_card_name', models.CharField(max_length=200)),
                ('activity_list_col1', models.TextField()),
                ('activity_list_col2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Travel_By_Activity_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_image', models.ImageField(upload_to='home_Travel_By_Activity_Event')),
                ('activity_name', models.CharField(max_length=200)),
                ('tour_count', models.CharField(max_length=200)),
            ],
        ),
    ]
