# Generated by Django 4.2.4 on 2024-07-08 05:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage_flight_offer',
            name='catchline',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
