# Generated by Django 4.2.4 on 2024-07-08 06:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_landingpage_flight_offer_catchline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage_hotel_offer',
            name='hotel_name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='landingpage_hotel_offer',
            name='hotel_rating',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
