# Generated by Django 4.2.4 on 2024-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_landingpage_hotel_offer_hotel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage_hotel_offer',
            name='hotel_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpage_hotel_offer',
            name='hotel_rating',
            field=models.CharField(max_length=200),
        ),
    ]
