# Generated by Django 4.2.4 on 2024-07-08 08:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_alter_landingpage_hotel_offer_hotel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage_travel_by_activity_card',
            name='activity_list_col1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='landingpage_travel_by_activity_card',
            name='activity_list_col2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
