# Generated by Django 4.2.4 on 2024-07-08 08:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_alter_landingpage_travel_by_activity_card_activity_list_col1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage_advertise_card1',
            name='advertise_card_catchline',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
