# Generated by Django 4.2.4 on 2024-07-08 08:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_alter_landingpage_advertise_card1_advertise_card_catchline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage_stories',
            name='story1_name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='landingpage_stories',
            name='story2_name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='landingpage_stories',
            name='story3_name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='landingpage_stories',
            name='story4_name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
