# Generated by Django 4.2.4 on 2024-07-08 09:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_alter_landingpage_stories_story1_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPage_Advertise_card2',
        ),
        migrations.AddField(
            model_name='landingpage_stories',
            name='story5_image',
            field=models.ImageField(default=' ', upload_to='home_Stories'),
        ),
        migrations.AddField(
            model_name='landingpage_stories',
            name='story5_name',
            field=ckeditor.fields.RichTextField(default='xx'),
        ),
    ]
