# Generated by Django 4.2.4 on 2024-07-08 09:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_delete_landingpage_advertise_card2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage_stories',
            name='story5_image',
            field=models.ImageField(upload_to='home_Stories'),
        ),
        migrations.AlterField(
            model_name='landingpage_stories',
            name='story5_name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
