# Generated by Django 4.2.4 on 2024-07-08 12:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_alter_landingpage_stories_story5_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage_About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title1', ckeditor.fields.RichTextField()),
                ('about_us_content1', ckeditor.fields.RichTextField()),
                ('about_us_image1', models.ImageField(upload_to='home_About_Us')),
                ('about_us_title2', ckeditor.fields.RichTextField()),
                ('about_us_content2', ckeditor.fields.RichTextField()),
                ('about_us_image2', models.ImageField(upload_to='home_About_Us')),
            ],
        ),
    ]
