# Generated by Django 4.2.4 on 2024-07-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_aboutpage_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage_about_us',
            name='about_us_image1',
            field=models.ImageField(upload_to='About_Us'),
        ),
        migrations.AlterField(
            model_name='aboutpage_about_us',
            name='about_us_image2',
            field=models.ImageField(upload_to='About_Us'),
        ),
    ]
