# Generated by Django 4.2.4 on 2024-07-09 05:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_alter_aboutpage_about_us_about_us_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage_Know_More',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(upload_to='About_Know_More')),
                ('card_text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
