# Generated by Django 4.2.4 on 2024-07-09 09:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_privacypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
