# Generated by Django 4.2.4 on 2024-07-10 10:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_termspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ImageField(upload_to='footer-logo')),
                ('footer_catchline', models.CharField(max_length=50)),
                ('footer_facebook_link', models.CharField(max_length=100, null=True)),
                ('footer_twitter_link', models.CharField(max_length=100, null=True)),
                ('footer_instagram_link', models.CharField(max_length=100, null=True)),
                ('footer_address', models.CharField(max_length=50)),
                ('footer_phone_number', models.CharField(max_length=15)),
                ('footer_email', models.CharField(max_length=50)),
                ('footer_copyright_line', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
