# Generated by Django 4.2.4 on 2024-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_facebook_link',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_instagram_link',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_twitter_link',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
