# Generated by Django 4.2.4 on 2024-07-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_alter_footer_footer_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='created_at',
        ),
    ]
