# Generated by Django 4.2.4 on 2024-07-12 05:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0019_footer_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage_Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_headimage', models.ImageField(upload_to='Career_Head')),
                ('career_headtitle', ckeditor.fields.RichTextField()),
                ('career_headcontent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
