# Generated by Django 4.2.4 on 2024-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0020_careerpage_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage_Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits_image', models.ImageField(upload_to='Career_Benefits')),
                ('benefits_content', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
