# Generated by Django 4.2.4 on 2024-07-12 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0021_careerpage_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=50)),
                ('Job_Location', models.CharField(max_length=100)),
                ('Experience_Required', models.CharField(max_length=50)),
                ('Job_Position', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
                ('Qualification_Required', models.TextField()),
                ('Job_Type', models.CharField(max_length=100)),
                ('Job_Description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
