# Generated by Django 4.2.4 on 2024-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0022_careerpage_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpage_job',
            name='Post_status',
            field=models.CharField(default='show', max_length=10),
        ),
    ]
