# Generated by Django 4.2.4 on 2024-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0024_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage_Apply_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('LinkedIn', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='resume-pdf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
