# Generated by Django 4.2.4 on 2024-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0025_careerpage_apply_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duffel_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('adults', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address_line_one', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('photos', models.JSONField()),
                ('amenities', models.JSONField()),
                ('review_score', models.FloatField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
