# Generated by Django 4.2.4 on 2024-08-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0028_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
